<?php

function ellie_extras_ds_pre_render_alter(&$layout_render_array, $context, &$variables)
{

    if (isset($variables['classes_array']) && !empty($variables['classes_array']))
    {
        $classes = $variables['classes_array'];

        $strip = array('panel', 'pane', 'entity', 'content', 'view');

        foreach($classes AS $key => $class)
        {
            $delimiter = strpos($class, '-');
            $prefix = substr($class, 0, $delimiter);

            if(in_array($class, $strip) || in_array($prefix, $strip))
            {
                unset($classes[$key]);
            }
        }

        if(!empty($classes))
        {
            $classes = array_merge($classes);
        }

        $variables['classes_array'] = $classes;

    }

}

function ellie_extras_entity_view($entity, $type, $view_mode, $langcode)
{

    $allowed = array('node');

    if (user_is_anonymous() && $view_mode == 'full' && !in_array($type, $allowed) && _entity_is_page($type, $entity) )
    {
        drupal_goto('<front>', array(), '301');
    }

}

function ellie_extras_html_head_alter(&$head_elements)
{

    global $base_url;

    $default_theme = variable_get('theme_default', 'ymca_one');

    foreach($head_elements as $key => $element) 
    {
    
        if( !empty($element['#attributes']) ) 
        {

            if( array_key_exists('rel', $element['#attributes']) ) 
            {

                if($element['#attributes']['rel'] === 'shortcut icon') 
                {
                    
                    $ellie_settings = variable_get('ellie_settings', array());

                    if( isset($ellie_settings['active_theme_color']) )
                    {
                        
                        $faviconLink = drupal_get_path('theme', $default_theme) . '/favicons/' . $ellie_settings['active_theme_color'] . '/favicon.ico';

                        if( file_exists(DRUPAL_ROOT . '/' . $faviconLink) )
                        {
                            $head_elements[$key]['#attributes']['href'] = $base_url . '/' . $faviconLink;
                        }

                    }

                }

            }

        }

    }
    
}

function ellie_extras_preprocess_html(&$vars) 
{
    
    $ellie_settings = variable_get('ellie_settings', array());

    if( isset($ellie_settings['active_theme_color']) )
    {
        $vars['classes_array'][] = 'color-scheme-' . $ellie_settings['active_theme_color'];
    }

}

function _entity_is_page($type, $entity) 
{
    return (($uri = entity_uri($type, $entity)) && current_path() == $uri['path']);
}


